import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BadgeDollarSign,
  BadgePlus,
  BarChart3,
  Bell,
  Bot,
  Box,
  Brain,
  Building2,
  Calculator,
  CalendarCheck2,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Code,
  Code2,
  Compass,
  Cookie,
  Copy,
  Download,
  Edit3,
  Eye,
  EyeOff,
  FileCheck2,
  FilePlus,
  FileText,
  Filter,
  Globe,
  Heart,
  Info,
  Kanban,
  KeyRound,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Lock,
  LogOut,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  Minus,
  Moon,
  MoreHorizontal,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  PieChart,
  Plus,
  Printer,
  Receipt,
  RotateCcw,
  Search,
  Send,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Sparkles,
  Star,
  StarHalf,
  Sun,
  Swords,
  Table,
  Target,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  Trophy,
  User,
  UserPlus,
  Users,
  X,
  Zap,
} from 'lucide-react';
import { Figma, Github } from './brandIcons';

// Keyed by the kebab-case names used in the original markup (data-lucide="...").
// Add an entry here when a new icon is needed; only listed icons end up in the bundle.
export const iconMap = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'badge-dollar-sign': BadgeDollarSign,
  'badge-plus': BadgePlus,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'bot': Bot,
  'box': Box,
  'brain': Brain,
  'building-2': Building2,
  'calculator': Calculator,
  'calendar-check-2': CalendarCheck2,
  'check': Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'clock': Clock,
  'code': Code,
  'code-2': Code2,
  'compass': Compass,
  'cookie': Cookie,
  'copy': Copy,
  'download': Download,
  'edit-3': Edit3,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-check-2': FileCheck2,
  'file-plus': FilePlus,
  'file-text': FileText,
  'filter': Filter,
  'globe': Globe,
  'heart': Heart,
  'info': Info,
  'kanban': Kanban,
  'key-round': KeyRound,
  'layers': Layers,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'line-chart': LineChart,
  'lock': Lock,
  'log-out': LogOut,
  'megaphone': Megaphone,
  'menu': Menu,
  'message-square': MessageSquare,
  'mic': Mic,
  'minus': Minus,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'palette': Palette,
  'panel-left': PanelLeft,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'paperclip': Paperclip,
  'pie-chart': PieChart,
  'plus': Plus,
  'printer': Printer,
  'receipt': Receipt,
  'rotate-ccw': RotateCcw,
  'search': Search,
  'send': Send,
  'share-2': Share2,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'sliders': Sliders,
  'sparkles': Sparkles,
  'star': Star,
  'star-half': StarHalf,
  'sun': Sun,
  'swords': Swords,
  'table': Table,
  'target': Target,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'trophy': Trophy,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'x': X,
  'zap': Zap,
  'figma': Figma,
  'github': Github,
};
